### ISSUE TITLE
Browser-GUI on Linux (Mint) creating user folders at / (root) level

### ISSUE THREAD

**Issue by stevang** [MASQ-Project/browser-GUI#7]
[No config.toml, on LinuxMint]
sudo ./MASQNode –initialization

Log is written to /root/.local/share/MASQ/MASQNode_daemon_rCURRENT.log

**Is this a intentional behavior that the user folder that will be created starts at / (root)?** 
In Linux you normaly have your user data under  /home/
**By the way, where will the node expect a config.toml when i start it via sudo ./MASQNode –initialization ?**

When i am ready configuring the node via the Browser-GUI, i start the node and the node-data.db will be created in /stephan74/.local/share/MASQ/ropsten/
The Username of my main non-root user will be used now to create a folder in / (root) 
**Is this a intentional behavior that the user folder that will be created starts at / (root)? Why are the files all over the place in /root/.local… and /stephan74/.local… and not under my /home folder where user data normally has its place?**

2020-12-04T21:02:18.974 Thd1: INFO: WebSocketSupervisor: UI connected at 127.0.0.1:59674
2020-12-04T21:02:18.992 Thd1: ERROR: Daemon: Daemon is sending redirect error for blah message to UI 0: Node is not running
Log is written to /stephan74/.local/share/MASQ/ropsten/MASQNode_rCURRENT.log
Created new database at "/stephan74/.local/share/MASQ/ropsten/node-data.db"
Opened existing database at "/stephan74/.local/share/MASQ/ropsten/node-data.db"

**Is it a normal behavior that after generating a wallet and doing some settings in the Web-UI and coming back to the wallet window, you see the earning wallet only?**

Regards,
Stephan

**Comment by kauri-hero** [comment]
Thanks @stevang 
We are addressing this on the Node reop Project board, as Microoo also posted this as well
its under [GH-363](https://github.com/MASQ-Project/Node/issues/363)
https://github.com/MASQ-Project/Node/issues/363
